#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
    groupadd -g $GROUP_ID_RENDER render
    usermod -aG $GROUP_ID_RENDER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

. /var/www/html/.env
if [ "" == "${APP_KEY}" ]; then
    gosu $WWWUSER /usr/bin/composer install --working-dir=/var/www/html
    for i in $(seq 1 10); do
        echo "######## ...waiting for database"
        sleep 5
        /usr/bin/php /var/www/html/artisan migrate
        SUCCESS=$?
        [ $SUCCESS -eq 0 ] && break
    done
    if [ $SUCCESS -gt 0 ]; then
        echo "######## to many database errors... giving up"
        exit 1
    fi 
    /usr/bin/php /var/www/html/artisan key:generate
fi

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
